name: Build with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  gradle:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Run Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build
